"""
Project Name : Password Security Analyzer

Developer : Sanika Patil

Description :
This module performs password security analysis,
calculates password score, entropy,
estimated crack time and suggestions.
"""

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime
import os


def export_pdf(results):

    if not os.path.exists("reports"):
        os.makedirs("reports")

    filename = datetime.now().strftime(
        "reports/password_report_%Y%m%d_%H%M%S.pdf"
    )

    c = canvas.Canvas(filename, pagesize=letter)

    width, height = letter

    y = height - 60

    # ==========================
    # Title
    # ==========================

    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(300, y, "PASSWORD SECURITY REPORT")

    y -= 40

    c.setLineWidth(2)
    c.line(50, y, width - 50, y)
    c.setLineWidth(1)
    y -= 30

    # ==========================
    # Date
    # ==========================

    c.setFont("Helvetica", 11)

    c.drawString(
        50,
        y,
        "Generated On : "
        + datetime.now().strftime("%d-%m-%Y %I:%M:%S %p")
    )

    y -= 50

    # ==========================
    # Summary
    # ==========================

    c.setFillColorRGB(0,0,0.6)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Password Analysis Summary")
    c.setFillColorRGB(0,0,0)

    y -= 10
    c.line(50, y, 320, y)

    y -= 25

    c.setFont("Helvetica", 12)

    c.drawString(
        60,
        y,
        f"Overall Score      : {results['score']}/100"
    )

    y -= 25

    c.drawString(
        60,
        y,
        f"Strength           : {results['strength']}"
    )

    y -= 25

    c.drawString(
        60,
        y,
        f"Entropy            : {results['entropy']} bits"
    )

    y -= 25

    c.drawString(
        60,
        y,
        f"Crack Time         : {results['crack_time']}"
    )

    y -= 50

    # ==========================
    # Detailed Analysis
    # ==========================

    c.setFillColorRGB(0,0,0.6)
    c.setFont("Helvetica-Bold",16)
    c.drawString(50,y,"Detailed Analysis")
    c.setFillColorRGB(0,0,0)

    y -= 10
    c.line(50, y, 250, y)

    y -= 25

    c.setFont("Helvetica", 12)

    c.drawString(
        60,
        y,
        f"Length             : {results['length'][1]}"
    )

    y -= 22

    c.drawString(
        60,
        y,
        f"Uppercase          : {results['uppercase'][1]}"
    )

    y -= 22

    c.drawString(
        60,
        y,
        f"Lowercase          : {results['lowercase'][1]}"
    )

    y -= 22

    c.drawString(
        60,
        y,
        f"Numbers            : {results['number'][1]}"
    )

    y -= 22

    c.drawString(
        60,
        y,
        f"Special Character  : {results['special'][1]}"
    )

    y -= 22

    c.drawString(
        60,
        y,
        f"Common Password    : {results['common'][1]}"
    )

    y -= 45

    # ==========================
    # Suggestions
    # ==========================

    c.setFillColorRGB(0,0,0.6)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Suggestions")
    c.setFillColorRGB(0,0,0)

    y -= 10
    c.line(50, y, 180, y)

    y -= 25

    c.setFont("Helvetica", 12)

    for suggestion in results["suggestions"]:
        c.drawString(70, y, u"\u2022 " + suggestion)
        y -= 20

    # ==========================
    # Footer
    # ==========================

    c.setFont("Helvetica-Oblique", 9)

    c.drawCentredString(
        width / 2,
        45,
        "Generated by Password Security Analyzer | Python Project"
    )

    c.save()

    return filename